Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo N. Aggio
// Data atual  : 02/09/2023
Var
// Seção de Declarações das variáveis 

A,B,temp:inteiro

inicio

escreva("Digite o valor de A: ")
leia(A)

escreva("Digite o valor de B: ")
leia(B)

temp<-A
A<-B
B<-temp

escreva("Valores trocados: A = ", A, " e B = ", B)



Fimalgoritmo